name: PacketEventsTutorial
version: '1.0-SNAPSHOT'
main: org.braekpo1nt.packetEventsTutorial.PacketEventsTutorial
api-version: '1.21'

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true

